# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Deploy to Production server
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H reduct-experiments.humanassisted.ai >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          cat > ~/.ssh/id_rsa << EOL
          ${{ secrets.LANGLANG__PROD_PRIVATE_SSH_KEY }}
          EOL
          
          chmod 600 ~/.ssh/id_rsa && chmod 600 ~/.ssh/known_hosts
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./ punit@reduct-experiments.humanassisted.ai:/home/punit/reduct-experiments/
          ssh -i ~/.ssh/id_rsa punit@transcript.np.reduct.video << EOL
          cd /home/punit/reduct-experiments
          echo "Hello world"
          EOL
